### ISSUE TITLE
Currently the bundle is not installable

### ISSUE THREAD

**Issue by dimonixx** [taymiya/oroplatform#1]
[https://github.com/taymiya/oroplatform/blob/2dd1904d3aed040652f66ce6a46d902bf795687e/Migrations/Schema/v1_0/IbnabPmanagerBundle.php#L3](https://github.com/taymiya/oroplatform/blob/2dd1904d3aed040652f66ce6a46d902bf795687e/Migrations/Schema/v1_0/IbnabPmanagerBundle.php#L3)

[https://github.com/taymiya/oroplatform/blob/2dd1904d3aed040652f66ce6a46d902bf795687e/Migrations/Schema/v1_1/IbnabPmanagerBundle.php#L3](https://github.com/taymiya/oroplatform/blob/2dd1904d3aed040652f66ce6a46d902bf795687e/Migrations/Schema/v1_1/IbnabPmanagerBundle.php#L3)

1. The migrations above have same namespace
2. It looks like the migration are in wrong order. In v1_0 the table `ibnab_pmanager_template` does not exist yet, but a column being added to the table.

**Comment by dimonixx** [comment]
In [https://github.com/taymiya/oroplatform/blob/2dd1904d3aed040652f66ce6a46d902bf795687e/Migrations/Schema/v1_2/IbnabPmanagerBundle.php#L34](https://github.com/taymiya/oroplatform/blob/2dd1904d3aed040652f66ce6a46d902bf795687e/Migrations/Schema/v1_2/IbnabPmanagerBundle.php#L34) the table `ibnab_pmanager_template` is created once more -> this leads to an error.

**Comment by taymiya** [comment]
Is updated thanks
