### ISSUE TITLE
A template can't be saved

### ISSUE THREAD

**Issue by dimonixx** [taymiya/oroplatform#2]
The template table does not have the field `direction`.

[https://github.com/taymiya/oroplatform/blob/c5e49e27f34fdcf122e2c00de94132b1b1356c2a/Entity/PDFTemplate.php#L146](https://github.com/taymiya/oroplatform/blob/c5e49e27f34fdcf122e2c00de94132b1b1356c2a/Entity/PDFTemplate.php#L146)

**Comment by taymiya** [comment]
now is added to migration file
